use waffle;

insert into member(member_id, password, nickname, part)
values ('hyesungoh', '0414', '오혜성', 'admin'),
       ('hanni66', '0807', '김하은', 'admin'),
       ('hanseulhee', '0326', '한슬희', 'admin'),
       ('vact19', '0129', '조성우', 'admin'),
       ('hangillee', '0414', '이한길', 'admin'),
       ('hanhyunsoo', '0511', '한현수', 'admin'),
       ('mojitobar', '1203', '주동석', 'admin'),
       ('yujinkim1', '0602', '김유진', 'Mobile'),
       ('wangseohee', '0209', '왕서희', 'Mobile'),
       ('yimjeongyeon', '0927', '임정연', 'Backend'),
       ('myoungjinseo', '0306', '서명진', 'Backend'),
       ('sub101', '1010', '김수빈', 'Mobile'),
       ('hyeall', '0720', '곽성은', 'Backend'),
       ('jaegwans', '0517', '김재관', 'Web'),
       ('leehyunbok', '0905', '이현복', 'Backend'),
       ('devpark435', '1031', '박현렬', 'Mobile'),
       ('sinamong0620', '0620', '김신아', 'Web'),
       ('khj0426', '0426', '김효중', 'Web'),
       ('yehyeokbang', '1212', '방예혁', 'Backend'),
       ('dd-jiyun', '0815', '이지윤', 'Backend'),
       ('lgyn10', '1022', '이찬균', 'Web'),
       ('yeezinu', '0313', '이진우', 'Web'),
       ('yuj2n', '0313', '전유진', 'Web'),
       ('jkkj0414', '0414', '김자경', 'Backend'),
       ('tndusy27', '0427', '김수연', 'Backend'),
       ('zoeyourlife', '0909', '최재훈', 'Web'),
       ('rltgjqmtkdydwk', '1107', '김은총', 'Mobile'),
       ('lee2eunji', '0817', '이은지', 'Web'),
       ('kikingki', '0212', '이지선', 'Backend'),
       ('qwe916', '0916', '전홍영', 'Backend'),
       ('jiyoungmerong', '0719', '허지영', 'Backend'),
       ('ParkSY0919', '0919', '박신영', 'Mobile'),
       ('parkjinhee53', '0503', '박진희', 'Mobile'),
       ('negul3', '0322', '김가현', 'Backend'),
       ('yeaseul7', '0327', '이예슬', 'Web'),
       ('baeksehee', '0909', '백세희', 'Web');

insert into member_roles(member_member_id, roles)
values ('hyesungoh', 'ADMIN'),
       ('hanni66', 'ADMIN'),
       ('vact19', 'ADMIN'),
       ('mojitobar', 'ADMIN'),
       ('hanhyunsoo', 'ADMIN'),
       ('hanseulhee', 'ADMIN'),
       ('hangillee', 'ADMIN'),
       ('yujinkim1', 'MEMBER'),
       ('wangseohee', 'MEMBER'),
       ('yimjeongyeon', 'MEMBER'),
       ('myoungjinseo', 'MEMBER'),
       ('sub101', 'MEMBER'),
       ('hyeall', 'MEMBER'),
       ('jaegwans', 'MEMBER'),
       ('leehyunbok', 'MEMBER'),
       ('devpark435', 'MEMBER'),
       ('sinamong0620', 'MEMBER'),
       ('khj0426', 'MEMBER'),
       ('yehyeokbang', 'MEMBER'),
       ('dd-jiyun', 'MEMBER'),
       ('lgyn10', 'MEMBER'),
       ('yeezinu', 'MEMBER'),
       ('yuj2n', 'MEMBER'),
       ('jkkj0414', 'MEMBER'),
       ('tndusy27', 'MEMBER'),
       ('zoeyourlife', 'MEMBER'),
       ('rltgjqmtkdydwk', 'MEMBER'),
       ('lee2eunji', 'MEMBER'),
       ('kikingki', 'MEMBER'),
       ('qwe916', 'MEMBER'),
       ('jiyoungmerong', 'MEMBER'),
       ('ParkSY0919', 'MEMBER'),
       ('parkjinhee53', 'MEMBER'),
       ('negul3', 'MEMBER'),
       ('yeaseul7', 'MEMBER'),
       ('baeksehee', 'MEMBER');